# Generated by Django 5.0 on 2023-12-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_created',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images'),
        ),
        migrations.AddField(
            model_name='listing',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
