# Generated by Django 5.0 on 2023-12-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_date_created_listing_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
    ]
