# Generated by Django 5.0 on 2023-12-19 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_winner_alter_listing_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_list', to='auctions.listing'),
        ),
    ]
