# Generated by Django 5.0 on 2023-12-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_watchlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='product',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='w_list', to='auctions.listing'),
        ),
    ]
