# Generated by Django 5.0 on 2023-12-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='product',
        ),
        migrations.AddField(
            model_name='listing',
            name='product_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.categorie'),
        ),
    ]
