# Generated by Django 5.0 on 2023-12-21 18:21

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_categorie_product_listing_product_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[100, None], upload_to='files/images'),
        ),
    ]
